package com.sample
 
import com.sample.DroolsTest.Answer
import com.sample.DroolsTest.GUI
import java.util.List
import java.util.ArrayList
import java.util.Arrays

global GUI gui

rule "[1] Are you bankrolling this entire enterprise, player?"
	when
		Answer(
			question == "Are you about to snap under the crushing weight of constant whining?" &&
			answer == "She just won't stop. MAKE IT STOP."
		)
	then
		String question = "Are you bankrolling this entire enterprise, player?";
		List<String> answers = new ArrayList<>();
		answers.add("They pay half, I pay half. JK, i pay for most of it.");
		answers.add("Yes, against all scientific odds I'm made of money.");
		answers.add("No, my kid's take-home pay is higher than mine, so he's paying for all of it.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[3] Do you mind if your kid never looks up from her phone again?"
	when
		Answer(
			question == "Has she ever has a phone?" &&
			answer == "No, but I feel like she needs it."
		)
	then
		String question = "Do you mind if your kid never looks up from her phone again?";
		List<String> answers = new ArrayList<>();
		answers.add("Actually, I have strict rules about the amount of time she will spend on her phone.");
		answers.add("One sec, I'm just finishing a game of Bejeweled");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[4] How will you feel when your kid drops and smashes the phone one the first day he has it?"
	when
		Answer(
			question == "Has she ever has a phone?" &&
			answer == "She's taking my phone too often. Should I hide it?"
		)
	then
		String question = "How will you feel when your kid drops and smashes the phone one the first day he has it?";
		List<String> answers = new ArrayList<>();
		answers.add("Now it looks like my phone. Neat!");
		answers.add("Excuse me while I curl up in a ball and weep.");
		answers.add("Fine. I am a husk of my former self. I feel nothing.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[5] Just the one phone?"
	when
		Answer(
			question == "Has she ever has a phone?" &&
			answer == "She already has an old one."
		)
	then
		String question = "Just the one phone?";
		List<String> answers = new ArrayList<>();
		answers.add("Dude. This isn't The Wire. How many phones does she need?");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[6] Who will spend their hard-earned cash on apps, overages and other charges your kid makes 'by mistake'?"
	when
		Answer(
			question == "Are you bankrolling this entire enterprise, player?" &&
			 (answer == "They pay half, I pay half. JK, i pay for most of it." ||
			 answer == "Yes, against all scientific odds I'm made of money.")
		  )
	then
		String question = "Who will spend their hard-earned cash on apps, overages and other charges your kid makes \"by mistake\"?";
		List<String> answers = new ArrayList<>();
		answers.add("She will. I mentioned it twice, so i think she gets it.");
		answers.add("Whatever, I'm a human ATM.");	
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[13] Mmm-hmm. What will you do next year when she wants a new phone?"
	when
		Answer(
			question == "Do you think she will answer your urgent calls and texts right away/quickly/ever?" &&
			answer == "No. It's like I'm invisible. Can you see me?"
		)
	then
		String question = "Mmm-hmm. What will you do next year when she wants a new phone?";
		List<String> answers = new ArrayList<>();
		answers.add("Whatever. I'm a human ATM.");
		answers.add("I will tell the story of how we used to land lines. And make her clean out the garbage.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[A] DON'T GET A PHONE. Why not spend that money on a Disney cruise? That should buy you at least a year."
	when
		Answer(
			(question == "Are you about to snap under the crushing weight of constant whining?" &&
			answer == "Actually, he never brought it up. I was just thinking...")
			||
			(question == "Are you going to shell out extra money for Apple Care, extra insurance or an unbreakable case?" &&
			answer == "Is there an unbreakable case I can shove my kid into?")
			||
			(question == "Will you pony up and get him another phone?" &&
			answer == "What? NO. Get a job, you mooch.")
		)
	then
		String question = "DON'T GET A PHONE. Why not spend that money on a Disney cruise? That should buy you at least a year.";
		insert( new Answer(question, "exit") );
end

rule "[B] GET THE PHONE AND DON'T LOOK BACK! You're aware of all of the frustrations, tears and money you'll go through, but it's still worth it. It's like having kids, except phones are way cooler."
	when 
		Answer(
			(question == "If you say yes, can you use this as leverage to get something you want?" &&
			answer == "Sweet. I can get a hot tub in the backyard!")
			||
			( (question == "Who will spend their hard-earned cash on apps, overages and other charges your kid makes \"by mistake?\"" 
				|| question == "Will you pony up and get him another phone?"
				|| question == "Are you going to shell out extra money for Apple Care, extra insurance or an unbreakable case?"
				|| question == "Mmm-hmm. What will you do next year when she wants a new phone?") &&			
			answer == "Whatever. I'm a human ATM.")
		)
	then
		String question = "GET THE PHONE AND DON'T LOOK BACK! You're aware of all of the frustrations, tears and money you'll go through, but it's still worth it. It's like having kids, except phones are way cooler.";
		insert( new Answer(question, "exit") );
end

rule "[C] WHY ARE YOU EVEN ASKING? Get a phone, live your life and savour this beautiful time together."
	when
		Answer(
			(question == "Have you also promised her a puppy?" &&
			answer == "Yes. Finally, I shall be crowned as the greatest parent ever. Bow to me!")
			||
			(question == "Are you bankrolling this entire enterprise, player?" &&
			answer == "No, my kid's take-home pay is higher than mine, so he's paying for all of it.")
		)	
	then
		String question = "WHY ARE YOU EVEN ASKING? Get a phone, live your life and savour this beautiful time together.";
		insert( new Answer(question, "exit") );
end
		
rule "[D] BUY KEVIN A PHONE! And congrats on creating your own A.I. Can you build me a Kevin too?"
	when 
		Answer(
			question == "Do you have a HUMAN child?" &&
			answer == "Kinda? I have a robot I built in my basement. I named him Kevin."
		)
	then
		String question = "BUY KEVIN A PHONE! And congrats on creating your own A.I. Can you build me a Kevin too?";
		insert( new Answer(question, "exit") );
end

rule "[0] Has she ever had a phone?"
	when
	then
		String question = "Has she ever had a phone?";
		List<String> answers = new ArrayList<>();
		answers.add("No but she's always wanted one.");
		answers.add("No but I feel like she needs it");
		answers.add("She's taking my phone too often. Should I hide it?");
		answers.add("She already has an old one");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[2] Are you about to snap under the crushing weight of constant whining?"
	when
	then
		String question = "Are you about to snap under the crushing weight of constant whining?";
		List<String> answers = new ArrayList<>();
		answers.add("Yes. This is all my kid talks about. I am slowly dying.");
		answers.add("Actually, he never brought it up. I was just thinking...");
		answers.add("She just won't stop. MAKE IT STOP");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end
		
		
rule "[7] HA HA good one. Do your kids always follow your rules?"
	when
		Answer(
			(question == "Do you mind if your kid never looks up from her phone again?" &&
			answer == "Actually, I have strict rules about the amount of time she will spend on her phone")
			||
			(question == "Do you think she will answer your urgent calls and texts right away/quickly/ever?" &&
			answer == "I found this cel phone agreement online. She signed it, so I think we're good")
		)
	then
		String question = "HA HA good one. Do your kids always follow your rules?";
		List<String> answers = new ArrayList<>();
		answers.add("HELL YEAH. They better");
		answers.add("Of course. They are my sweet angels <3.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[8] Can you handle him losing his phone like, LITERALLY everywhere?"
	when
		Answer(
			(question == "Do you mind if your kid never looks up from her phone again?" &&
			answer == "On sec, I'm just finishing a game of Bejeweled")
			||
			(question == "Do you think she will answer your urgent calls and texts right away/quickly/ever?" &&
			answer == "No. It's like I'm invisible. Can you see me?")
		)
	then
		String question = "Can you handle him losing his phone like, LITERALLY everywhere?";
		List<String> answers = new ArrayList<>();
		answers.add("Hang on. I can't find my phone. Can you call it?");
		answers.add("Nope. SHUT ID DOWN");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[9] Are you seriously shocked that he lost his phone?"
	when
		Answer(
			question == "Can you handle him losing his phone like, LITERALLY everywhere?" &&
			(answer == "Hang on. I can't find my phone. Can you call it?" ||
			answer == "Nope. SHUT IT DOWN.")
		)
	then
		String question = "Are you seriously shocked that he lost his phone?";
		List<String> answers = new ArrayList<>();
		answers.add("I guess not. Just leave me alone and let me drink.");
		answers.add("This is my first dat with my kid. We're still getting to know each other.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[10] Do you think she will answer your urgent calls and texts right away/quickly/ever?"
	when
		Answer(
			question == "HA HA good one. Do your kids always follow your rules?" &&
			answer == "HELL YEAH. They better."
		)
	then
		String question = "Do you think she will answer your urgent calls and texts right away/quickly/ever?";
		List<String> answers = new ArrayList<>();
		answers.add("No. It's like I'm invisible. Can you see me?");
		answers.add("I found this cell phone agreement online. She signed it, so I think we're good.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[11] Do you and your kid know about bullying?"
	when
		Answer(
			question == "Are you about to snap under the crushing weight of constant whining?" &&
			answer == "Yes. This is all my kid talks about. I am slowly dying."
		)
	then
		String question = "Do you and your kid know about bullying?";
		List<String> answers = new ArrayList<>();
		answers.add("Um, yeah. Doi.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[12] Will you pony up and get him another phone?"
	when
		Answer(
			(question == "Are you seriously shocked that he lost his phone?" &&
			answer == "I guess not. Just leave me alone and let me drink." || 
			answer == "This is my first dat with my kid. We're still getting to know each other.")
			||
			(question == "How will you feel when your kid drops and smashes the phone one the first day he has it?" &&
			answer == "Now it looks like my phone. Neat!" ||
			answer == "Excuse me while I curl up in a ball and weep." || 
			answer == "Fine. I am a husk of my former self. I feel nothing.")
		)
	then
		String question = "Will you pony up and get him another phone?";
		List<String> answers = new ArrayList<>();
		answers.add("Yes, but he will work it off with hard manual labour around the house until the end of days.");
		answers.add("What? NO. Get a job, you mooch.");
		answers.add("Whatever. I'm a human ATM.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );		
end

rule "[14] Do you have a HUMAN child?"
	when
		Answer(
			(question == "Who will spend their hard-earned cash on apps, overages and other charges your kid makes \"by mistake?\"" &&
			answer == "She will. I mentioned it twice, so I think she gets it.")
			||
			(question == "HA HA good one. Do your kids always follow your rules?" &&
			answer == "Of course. They are my sweet angels <3.")
		)
	then
		String question = "Do you have a HUMAN child?";
		List<String> answers = new ArrayList<>();
		answers.add("Kinda? I have a robot I build in my basemenent. I named him Kevin.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[15] Are you being bullied right now?"
	when
		Answer(
			question == "Do you and your kid know about bullying" &&
			answer == "Um, yeah. Doi."
		)
	then
		String question = "Are you being bullied right now?";
		List<String> answers = new ArrayList<>();
		answers.add("Yes. Hold me.");
		answers.add("No more than usual");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[16] If you say yes, can you use this as leverage to get something you want?"
	when 
		Answer(
			(question == "Are you being bullied right now?" &&
			answer == "No more than usual.")
			||
			(question == "Have you also promised her a puppy?" &&
			answer == "No. I mean, maybe? IDK, I'm so tired.")
		)
	then
		String question = "If you say yes, can you use this as leverage to get something you want?";
		List<String> answers = new ArrayList<>();
		answers.add("Sweet. I can get a hot tub in the backyard!");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[17] Have you also promised her a puppy?"
	when 
		Answer(
			question == "Are you being bullied right now?" &&
			answer == "Yes. Hold me."
		)
	then 
		String question = "Have you also promised her a puppy?";
		List<String> answers = new ArrayList<>();
		answers.add("No. I mean, maybe? IDK, I'm so tired.");
		answers.add("Yes. Finally, I shall be crowned as the greatest parent ever. Bow to me!");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "[18] Are you going to shell out extra money for Apple Care, extra insurance cor an unbreakable case?"
	when
		Answer(
			(question == "Will you pony up and get him another phone?" &&
			answer == "Yes, but he will work it off with hard manual labour around the house until the end of days.")
			||
			(question == "Mmm-hmm. What will you do next year when she wants a new phone?" &&
			answer == "I will tell the story of how we used to land lines. And make her clean out the garbage.")
		)
	then
		String question = "Are you going to shell out extra money for Apple Care, extra insurance cor an unbreakable case?";
		List<String> answers = new ArrayList<>();
		answers.add("Is there an unbreakable case I can shove my kid into?");
		answers.add("Whatever. I'm a human ATM.");
		String choice = gui.display(question, answers);
		insert( new Answer(question, choice) );
end

rule "Exit"
	when
		ans: Answer(answer == "exit")
	then
		List<String> answers = new ArrayList<>();
		answers.add("Done :- )");
		gui.display(ans.question, answers);
		gui.dispose();
end



